name: main

on:
  push:
    branches:
      - '+([0-9])?(.{+([0-9]),x}).x'
      - 'master'
      - 'next'
      - 'next-major'
      - 'beta'
      - 'alpha'
  pull_request: {}

jobs:
  validate:
    name: validate
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile

      - name: Test
        run: yarn test

  release:
    name: release
    needs: [validate]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && github.event.repository.full_name == github.repository &&
      contains('refs/heads/master,refs/heads/beta,refs/heads/next,refs/heads/alpha', github.ref)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
